# This is the master config for the application.
# It is loaded from within environment.rb using config/application_config.rb
# 
# These configuration parameters are ultimately accessed by the application through a hash named $APP_CONFIG
--- 
global:   # these global values are used for all environments, they can be overriden by individual environment settings
          #
  :search:
    :polling_interval_s:          5    # polling interval for new jobs
    :search_delay_interval_s:     5    # minimum seconds between searches
    :minimum_search_interval_s:   5    # number of seconds that must pass before the same search can be executed again
    :use_threading: true
    :ts_debug_level: 0

  :admin: 
    :email_recipients: 
    - Bill Doughty <billdoughty@capitalthought.com>
    :email_sender: 
    - BuzzVoter.com <noreply@buzzvoter.com>

  :system_alerts:         # configuration for system alerts manager
  
  :twitter:
    :login: buzzvoter
    :password: otherinbox2008
    :stub_tweets: false     # if true, tweets will be logged instead of being sent
    
  :css:
    # :stylesheet: buzzvoter_dark
    :stylesheet: buzzvoter
      
beta: 
  :search:
    
  :site: 
    :protocol: http
    :host_name: betabuzz
    :domain: capitalthought.com
    
development: 
  :search: 
    :polling_interval_s:          5    # polling interval for new jobs
    :ts_debug_level: 4
    :use_threading: false
    :minimum_search_interval_s:   10    # number of seconds that must pass before the same search can be executed again

  :site: 
    :protocol: http
    :host_name: localhost
    :domain: local.org
    :port: "3002"
    
  :admin: 
    :email_sender: 
    - BV Development <noreply@buzzvoter.com>

  :twitter:
    :stub_tweets: false     # if true, tweets will be logged instead of being sent
    
production: 

  :site: 
    :protocol: http
    :domain: buzzvoter.com

test: 
  :search: 
    :use_threading: false
    :ts_debug_level: 0
    :polling_interval_s:         0   # polling interval for new jobs
    :search_delay_interval_s:    0   # minimum seconds between searches
    :minimum_search_interval_s:  0    # number of seconds that must pass before the same search can be executed again
  
  :site: 
    :protocol: http
    :site_url: http://
